server:
  port: 8082

spring:
  application:
    name: pos-cart

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: pos-cart
    prefer-ip-address: true
