openapi: "3.0.0"

info:
  version: 1.0.0
  title: User
  license:
    name: MIT
paths:
  /order:
    post:
      summary: send an order
      operationId: sendOrder
      tags:
        - order
      requestBody:
        description: an order infos
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        '200':
          description: A boolean result of adding operation
          content:
            application/json:
              schema:
                type: boolean
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"




components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    User:
      type: object
      required:
        - uid
      properties:
        uid:
          type: string
        password:
          type: string
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: double
        image:
          type: string
    Item:
      type: object
      required:
        - product
        - quantity
      properties:
        product:
          $ref: "#/components/schemas/Product"
        quantity:
          type: integer
    Cart:
      type: array
      items:
        $ref: "#/components/schemas/Item"
    Order:
      type: object
      required:
        - user
        - cart
      properties:
        user:
          $ref: "#/components/schemas/User"
        cart:
          $ref: "#/components/schemas/Cart"