server:
  port: 8081

spring:
  application:
    name: pos-products

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: pos-products
    prefer-ip-address: true