server:
  port: 8083
spring:
  application:
    name: pos-counter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: pos-counter
    prefer-ip-address: true