server:
  port: 8086
spring:
  application:
    name: pos-checker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: pos-checker
    prefer-ip-address: true
