server:
  port: 6001
spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      routes:
        - id: pos-products
          uri: lb://pos-products
          predicates:
            - Path=/api/products/**
            - Method=GET
        - id: pos-cart
          uri: lb://pos-cart
          predicates:
            - Path=/api/cart/**
        - id: pos-counter
          uri: lb://pos-counter
          predicates:
            - Path=/api/login/**
        - id: pos-order
          uri: lb://pos-order
          predicates:
            - Path=/api/order/**
        - id: check
          uri: lb://pos-checker
          predicates:
            - Path=/check/**
  main:
    web-application-type: reactive
eureka:
  instance:
    instance-id: pos-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka